### PR TITLE
improve README / front page text

### LINKED ISSUE #330: Front page
We got a tip from Communications:

> On the first page, in bold, it tells the audience to read the Turing Way instead. Most people might tune out immediately and do just that instead of exploring the website. It’s never really a good idea to direct visitors away from your site, especially on the landing page. We would recommend you highlight the differences between our guide and the Turing Way in a more balanced way.

I think I agree we could write this better. Suggestions?

### PR DESCRIPTION
**Pull request by egpbos**
Fixes #330.

# Checklist

## SIGNIFICANT changes / additions, e.g. new chapters
- [x] I discussed my contribution in an issue and took into account feedback.

## ALL contributions
- [x] I previewed my changes locally using e.g. `python3 -m http.server 4000` and confirmed they work correctly.
- [x] I checked for broken links, e.g. using the link checker GitHub Action workflow, or locally by using ``docker run --init -it -v `pwd`:/docs lycheeverse/lychee /docs --config=docs/lychee.toml``, at least for the files I changed.
- [x] My name was added to the `CITATION.cff` file.

### CODE REVIEW

**Comment by egpbos** [comment]
I had a chat with @VeronicaWYPang and she gave some great suggestions that I will implement now. Please hold off on reviewing the current stuff for the moment!

**Comment by egpbos** [comment]
Ready for review!

**Comment by egpbos** [comment]
Veronica approved this via mail :)

**Review by c-martinez — APPROVED** [review]
Thank you @VeronicaWYPang !

**Pull request merged**
