### PR TITLE
update Python editors & IDEs section

### PR DESCRIPTION
**Pull request by egpbos**
Small update for the editors and IDEs. I don't think anybody uses atom, sublime or PyDev anymore, so I removed them. Added vscode.

### CODE REVIEW

**Comment by egpbos** [comment]
Note to reviewer: the link checker is failing because of dead links in master. We should make a separate PR to fix them.

**Review by bouweandela — CHANGES_REQUESTED** [review]
To me, visual studio code looks a lot more like an IDE than a text editor. Did I miss something here? Do we still recommend using PyCharm over vscode?

I personally know at least one person who is very happy using sublime, but I'm fine with removing it.

**Comment by egpbos** [comment]
Ah, haha, Sublime, man, that takes me back ;) I loved it (even bought a license), and it was certainly superior to Atom, the sluggish Sublime clone, but to me there is no point anymore now that VSCode exists, which is both fast and open and as feature rich as Sublime was (and more, I think).

In any case, it's true that it is perhaps weird to mention vim and VScode, but not other editors. I'm not sure why we need to mention editors at all tbh. I think people are more than capable to find their own favorites. What do you think, should we just remove it?

Today, by coincidence, I just started up PyCharm again, because I'm dealing with an annoying bug, and I like the debugger in PyCharm better than VSCode, which still feels clumsy to me. But I admit that this too may be very personal and may also be due to me having worked a lot with CLion, another Jetbrains IDE, so PyCharm feels familiar to me.

Anyway, I think also in this case we can fight long battles.

My general approach would be: if people feel strongly about adding an editor, they're free to. I was just cleaning up what I thought was old an unused. I personally like VSCode, vim and PyCharm, so I left them in. If you want to keep Sublime in, fine by me too.

What say yee? :)

**Comment by LourensVeen** [comment]
I'd say that this is something personal, and also something that doesn't matter for collaboration. If you want to use VSCode and I want to use vim, then we can still easily cooperate on a program. With editorconfig, we can even share a single formatting configuration. So let everybody use whatever they like.

What I do think might be useful is a list of at least some options that some of us like. That way, if you're new to a language and looking around in bewilderment trying to figure out where to start, at least you can easily play with a few non-terrible options to see which you like best.

**Comment by egpbos** [comment]
Agreed @LourensVeen. The list now includes options that I like. If someone else wants to add on to this PR, feel free, branch `python_editors`. If not, I'll merge it like this next week or so and let others add their own stuff later.

**Comment by jiskattema** [comment]
Maybe add that we do recommend using a proper editor?
For people just starting with coding, the benefits of using something like VSCode (linting, building, docs, autocompletion) are probably not obvious.

**Comment by bouweandela** [comment]
I agree with @LourensVeen that it is nice to have a list of popular choices. What I do not like is the distinction that is made here between editors and IDEs. Can we just flatten the list, e.g. like this:

Popular editors and IDEs
---------------------------------
- vscode
- pycharm
- vim (don't forget to install the plugins)
- emacs (don't forget to install the plugins)
- ..

**Comment by jiskattema** [comment]
However much i love vim ; i'm not sure we should recommend it to people that just start programming (with possibly a windows background..). Same for emacs. 
A warning that those are advanced 'productivity' tools and would require some investment to get started would be good.

**Comment by bouweandela** [comment]
That might be true, but many people of beginner level who are developing on an HPC machine because they only have a windows desktop to ssh from will use emacs and or vi for their code editing. It is really useful if they are aware that there are plugins available for linting.

**Comment by egpbos** [comment]
Ok, let me approach this from another angle: should we maybe put editors in a separate chapter?

Instead of repeating all our favorite editors in every **language** chapter, it would perhaps be better if here we only list **specific tools for working with Python**.

For instance, linters exist for (almost) every language, as well as debugging and other plugins. We don't have to repeat that for every language, this is generic knowledge.

However, IDEs are language specific, so they are more relevant to mention. Also, there may be very specific plugins for editors that significantly improve the user experience for that particular language; that is worth mentioning in the language chapter as well. For VSCode, everything is already baked in (or it automatically suggests that you install it when you first open a Python file), so we definitely needn't mention anything about it here. I guess for a `vim`-adept, it is similar: obviously you'll look for a Python linting plugin and maybe some reference following thingy, but `vim`mers will figure that out themselves.

**Comment by bouweandela** [comment]
Maybe, but it seems a bit overengineered to create a completely new chapter for a list of just 4 items..

**Comment by egpbos** [comment]
True @bouweandela. Ok, well, I think everybody agrees that it's very personal. My personal view is incorporated in the PR as it stands. If anybody feels something is missing, feel free to add by opening a new PR. If somebody thinks that I am removing things that should not be removed, I will close the PR. Agreed?

**Comment by egpbos** [comment]
I addressed your review comments @bouweandela and hope to also have found a middle ground within the rest of this discussion that went back and forth ;) Please rereview :)

**Review by bouweandela — APPROVED** [review]

**Pull request merged**
