### PR TITLE
Guide2020

### PR DESCRIPTION
**Pull request by ehabdevel**
- [x] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

Below, describe what this Pull Request adds:

 Use VuePress to build a new guide.

### CODE REVIEW

**Comment by ehabdevel** [comment]
Screenshot from 2019-10-31 15-32-13
Screenshot from 2019-10-31 15-32-46
Screenshot from 2019-10-31 15-33-11

**Comment by bouweandela** [comment]
Hi @ehabdevel, thank you for your effort in putting in this pull request. Can you elaborate a bit on what it adds and why we would need this please?

**Comment by ehabdevel** [comment]
Hi @bouweandela ,
Thank you for your comment. in this pull request I choose VuePress cause it gives the most important needed features for the guide as I think.

What it adds and why we would need this?

- Better nice looking front-end.
- Easy looking navigation to keep clear structure as long as the guide pages grows.
- Mobile ready PWA.
- Easy for content contributors with just editing Markdown files and in the root directory.
+ The ability to add more from VuePress Features (https://vuepress.vuejs.org/guide/#features)

(The primary problem with GitBook is that its development reload performance is intolerable with a large amount of files. The default theme also has a pretty limiting navigation structure, and the theming system is, again, not Vue based. The team behind GitBook is also more focused on turning it into a commercial product rather than an open-source tool.) https://vuepress.vuejs.org/guide/#gitbook

**Comment by ehabdevel** [comment]
Sorry, Not editing Markdown files.

**Pull request closed without merging**
