### PR TITLE
Remove C from title

### PR DESCRIPTION
**Pull request by JensWehner**
the whole guideline is only about C++ and C and C++ are not the same thing.

- [x] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

Below, describe what this Pull Request adds:

Removed C from title

### CODE REVIEW

**Comment by bouweandela** [comment]
Why do we want to remove C from the title? There is some information about using C in the chapter.

**Comment by egpbos** [comment]
Hm, I'm not sure about this either. I see where it's coming from, the chapter is indeed written mainly from the C++ perspective. However, most of the tools (and even libraries) are very well usable for C as well. And, let's face it, C is not *that* different from what one might call the "C dialect" of C++, or C--, or whatever you like to call the way in which some C++ programs are written with only very limited object oriented, template or other C++ specific functionality, so in that sense C is more or less a subset of C++ (am I stepping on people's toes yet or did I phrase that carefully enough? :P). We could also just add a note at the beginning stating this caveat. I don't know if it makes sense to write a separate C chapter, it would probably be very short and could then refer to the C++ one for more information on tools like gdb, clang, etc. (a bit like the Fortran one).

**Comment by JensWehner** [comment]
Many C best practices are considered dangerous in C++. If this text is supposed to advise on good coding guidelines, the distinction between good C and good C++ should be made clearer. 

If I want information on C I have to read all the stuff that applies to C++. I see the convenience part to keep them together, but as a new user I find it misleading.

**Comment by egpbos** [comment]
Best practices is a fair point.

However, quickly scanning through the chapter again, it seems to me that everything up to the Style section is applicable to both C and C++, in some cases (build warnings) it's even explicitly separately mentioned.

Maybe we can add some info about good coding practices in both languages. This could be added to the part where the Google style guidelines etc are mentioned, I'd say.

We could even put that part at the top of the document, with a short intro text and referring to good books or other references for further details and learning for beginners.

**Comment by LourensVeen** [comment]
C libraries can and often are called from Fortran as well. Yes, C++ started life as C-with-classes, but that's a quarter of a century ago. Modern C++ has replaced pretty much the entire C API with better, safer C++ equivalents, and as Jens put it, we should not make it seem as if mixing in C with your C++ code is a good idea.

It's true that many of the tools listed here work with both C and C++, either because they're part of a toolchain that has frontends for many languages, or because they're language-agnostic. But everything that's been said here about C also goes for Fortran, and Fortran is not on this page.

Maybe we should consider making this a page on native development in general? In the end it's having binaries that tie all these things together, and the separate Fortran page doesn't add much.

**Comment by LourensVeen** [comment]
Or, make this page C++-specific, C++ being our preferred language for high-performance code, I think, and combine C and Fortran on one other page as second-class/legacy citizens. C and Fortran are closer than C and C++, in my view.

**Comment by JensWehner** [comment]
On the first 30 lines C is never mentioned. I simply felt, that this document is not about C. 
It feels misleading to me, but simply close the issue if you disagree. :)

**Comment by egpbos** [comment]
Makes sense @LourensVeen.

**Comment by egpbos** [comment]
No, I agree @jenswehner, we can make it a lot clearer.

**Comment by egpbos** [comment]
> C++ being our preferred language for high-performance code

At the risk of making this a too philosophical discussion ;) Let's say I'm not 100% behind this. I think once you go for highest performance, it's often not C++ style code you'll end up with. If you want to be really nice and safe and modern, you wouldn't use vector::operator[] for instance, but rather the safer but less performant vector::at (example from a random discussion I recently saw on Twitter). Modern C++ with the whole std lib tries to be platform independent, generic, safeish, even readable if you can see through all the keywords, and of course performant, but not necessarily in the sense of high maximum throughput performance. It seems nowadays to be more about the mantra of don't pay for what you don't use, which is a design focus mantra. C++ gives you tools to completely design the crap out of your code, at least compared to other high performance languages like C and Fortran. You get control.

If you just want performance, you often get to the hardware level and C++ in the modern sense is certainly not optimized for this. Probably C is better, or CUDA of course, depending on your hardware.

For completeness' sake, let me just add that from my experience working on ROOT, I would say that starting such a big OO-based code from scratch nowadays in C++ would be quite a horrible idea. Just use Python or whatever for glue between high performance modules. C++ is just such a huge thing and there's so many ways to do things that it's really overwhelming and I would say really hard to maintain. It's still a nice language imho, especially for smaller high performance projects, but beware not to let it grow beyond control :D

**Comment by bouweandela** [comment]
Hi Jens,

Maybe combining the two languages in one chapter indeed doesn't make sense, and you could try making a pull request where you make a separate C chapter? I guess you could solve the overlap in content by putting some links in the C chapter to the C++ chapter. Just removing C from the title seems a bit too quick though.

**Comment by LourensVeen** [comment]
@egpbos On the other hand, Eigen beats other linear algebra libraries on certain calculations because it uses expression templates, something that's definitely not C-ish or Fortran-ish.

I recently came across an agent-based simulation written in Python which has some pretty complex logic, and which I'm sure would be a lot faster if written in C, C++ or Fortran. Would you recommend they use something else than C++ if they need more performance? Or to use a struct and separate functions in C++ for performance?

**Comment by egpbos** [comment]
@LourensVeen expression templates are a good counterpoint, you're right, xtensor, armadillo, and probably others do the same. However, the template dialect of C++ has its own unique issues: hard to debug (walls of debug text), horrible syntax (`< < < < < < enable_if < blabla >.value, thing_one<stuff, more_stuff>, please_save_me<>>>>>` (`error, missing ">"`)), and lack of expressibility in the current syntax, i.e. your code will be 90% helper functions to solve some really simple things like if-statements. Not really easy to maintain or write, so maybe in the end the total time of the scientific project (development + generating results etc) will be longer than when you had used a simpler language with less performance. I'm not advocating for or against C++ or Python, but saying it's the HPC language of choice maybe goes a bit too far. Right tool for the job I would say, and of course also considering the skills of the engineer :) Maybe what I'm saying is: I would trust you to build a solid C++ framework from scratch, but maybe you shouldn't trust me to do that :D ;)

**Comment by LourensVeen** [comment]
So if you came to me and asked which language to use for performance-critical code, what should I say?

**Comment by egpbos** [comment]
"It depends" ;) My answer to such a generic question would be:

- If it's just numerical algorithms:
  - Try NumPy
  - If that's not good enough for some part of your code: try xtensor or similar to build a performance critical module that interfaces with NumPy
- If it's something more complex then it really depends on your skills and interests, but still I would say:
  - Do prototyping in a language you know really well.
  - If the whole thing is performance critical, implement the final version in C++.
  - If only parts are performance critical, maybe again do Python modules, but I'm not an expert in this area.

**Comment by JensWehner** [comment]
with C++17 and `constexpr if` it got a lot better with the templates. To be honest I do not like python because the dynamic typing drives me nuts. 

A new project would still be python because you get x times more contributions and 95% of the code is boilerplate anyway.

**Comment by bouweandela** [comment]
@JensWehner Is this pull request something you intend to work on? See my comment here for a possible way forward: https://github.com/NLeSC/guide/pull/207#issuecomment-621010716. Or can it be closed?

**Comment by JensWehner** [comment]
I intent to yes, but I do not know when. :)

**Comment by bouweandela** [comment]
@JensWehner Left NLeSC some time ago, so I guess this will never get done.

**Pull request closed without merging**
