### PR TITLE
Cpp chapter

### PR DESCRIPTION
**Pull request by jhidding**

### CODE REVIEW

**Comment by LourensVeen** [comment]
I agree with Patrick who said elsewhere that the disclaimer is not very good, but I don't like this intro much either. It's still somewhat negative, and also rather random. I'll take a shot at writing something later this afternoon if my tuit turns out sufficiently round.

**Comment by jhidding** [comment]
I agree. Still, there should be something saying: please be careful starting a project in C++. Please edit and improve as much as you can!

**Comment by LourensVeen** [comment]
How's this for an introduction?

> C++ may be the most complicated programming language in existence. It supports a variety of programming styles, including imperative, object oriented, functional, and generic programming. It lets you create very high-level abstractions, but it also gives you low-level primitives and direct control over memory. Its powerful type system can check for many errors at compile time, making your software safer, but it can also be ignored or overridden, resulting in dangerous code. Because of its versatility, C++ leaves you free to design your code in any way you want, but that also means that it does not guide you in any way.
> 
> In short, C++ is a very sharp tool. It can be used to create beautiful masterpieces, but it takes a long time to master, and while learning you're likely to cut yourself more than once. At the eScience Center, we work together with scientists and engineers with a wide variety of programming skills, including expert software engineers, but also domain scientists with only basic knowledge of programming. For most projects and new code, we therefore prefer simpler languages like Python or Java. However, if a project already uses C++, then any extensions we make will also be done in C++, and we will use C++ best practices to do so.

**Comment by jhidding** [comment]
Prima! Do you want to paste it yourself and get all the git-tree credits for this literary masterpiece?

**Comment by nielsdrost** [comment]
Awesome intro Lourens!

> For most projects and new code, we therefore prefer simpler languages like Python or Java.

I would change one word in this sentence and make it bold:

**For most projects and new code, we therefore recommend simpler languages like Python or Java.**

>However, if a project already uses C++, then any extensions we make will also be done in C++, and we will use C++ best practices to do so.

This is a bit too much of a contract: if a single line of C++ is present, all new code _must_ be C++ as well ;-)

However, if a project already uses C++, then any extensions we make will most likely also be done in C++, and we will use C++ best practices to do so.

**Comment by LourensVeen** [comment]
Glad you like it, I'll make a separate pull request with that text tomorrow.

**Comment by LourensVeen** [comment]
My intro is now #28.

**Pull request merged**
