### PR TITLE
reorganize chapters: add technology guides section

### LINKED ISSUE #335: Add tech chapters section
We should start reorganizing.

- [x] Add Technology Guides section (similar to Language Guides)
- [x] Move opencl_cuda.md there and rename it to GPU programming
- [x] Move UX there

### PR DESCRIPTION
**Pull request by egpbos**
# Changes in this PR

This PR adds the new section of technology guides and moves the GPU and UX chapters there.

Also moved language guides to the root folder level, because I find it annoying to have to click into the best_practices folder.

_Note: datasets still has to be moved to technologies, but there is an outstanding PR https://github.com/NLeSC/guide/pull/339 on that and I don't want to stress git's ability to detect moved files too much, otherwise we lose the ability to easily browse edit history._

Fixes #335.

### CODE REVIEW

**Comment by bouweandela** [comment]
@egpbos You've requested our review, but it is still in draft. Would you like me to review this now?

**Comment by egpbos** [comment]
Yes, you can review. The only thing that I still want to do before merging is move the dataset chapter as well, after #339 is merged, that's why it's still in draft.

**Review by bouweandela — DISMISSED** [review]
Would it make sense to move the language and technology guides above the best practices (which we're planning to delete anyway) in the sidebar?

The README.md still needs to be updated to reflect the changes here.

**Comment by egpbos** [comment]
Good catch, updated the README.

I would suggest to consider the Best Practices in another thread, because I'm not sure if we should completely remove it.

**Comment by egpbos** [comment]
Ah, we had that other thread already :P #321

**Comment by egpbos** [comment]
Ok, I moved it down as you suggested after all. Otherwise the technology menu is too far down and it may not be noticed.

**Review by c-martinez — APPROVED** [review]

**Comment by egpbos** [comment]
Assuming @bouweandela is happy with the changes, since he suggested them ;) Merging!

**Pull request merged**
