### PR TITLE
add Python debugging and Python logging

### PR DESCRIPTION
**Pull request by fdiblen**

### CODE REVIEW

**Comment by LourensVeen** [comment]
Ah, just what I needed :). Great work, thanks!

One comment: perhaps you could note which of the IDEs mentioned are open source? Free is a confusing term.

**Comment by fdiblen** [comment]
@jvdzwaan Travis fails because https://landscape.io and https://www.scipy.org are down for some reason.

**Comment by nielsdrost** [comment]
Yes, nice!

There is already an 'Editors and IDEs' section in the Python chapter. Perhaps add all the info on IDEs there, and only refer to that section?

Leave out the "www" for a working scipy site, see numpy/numpy#8779

**Comment by fdiblen** [comment]
@jvdzwaan @nielsdrost 
I think you can merge now. I added some extra info to visualization and Jupyter notebooks sections.

**Pull request merged**
