### PR TITLE
Replace GitBook with Docsify

### PR DESCRIPTION
**Pull request by sverhoeven**
- [x] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

Below, describe what this Pull Request adds:
Uses https://docsify.js.org/ instead of GitBook to render guide.

The guide can be viewed on a local clone on http://localhost:8000 by
```shell
git clone https://github.com/NLeSC/guide.git
cd guide
git checkout docsify
python3 -m http.server 8000
```

From what could see all pages render correctly and the search works.

Tasks, after PR merge, to complete switch:
1. Enable GitHub pages on master branch
2. Configure guide.esciencecenter.nl to point to GitHub pages, see [help](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)

### CODE REVIEW

**Comment by c-martinez** [comment]
Looks nice -- search works. But some internal links are not working:

e.g.: inside `/best_practices/checklist` "Pick & include an open source license" gives 404, while it should be pointing to `/best_practices/licensing`

**Comment by sverhoeven** [comment]
Doh, that is not very useful, will try to fix the internal links

**Comment by sverhoeven** [comment]
Links have been fixed and the link checker now directly checks the Markdoiwn files.

**Comment by c-martinez** [comment]
Links seem fine now. Some links seem broken, but they might have been broken for a while.

**Comment by bouweandela** [comment]
@jspaaks or @c-martinez Do you think this is ready to be merged?

**Comment by c-martinez** [comment]
Yes, it worked fine when I checked it -- I am not sure if @jspaaks has time to review it, but perhaps we can reassign reviewer to me?

**Comment by bouweandela** [comment]
Sure, thanks!

**Comment by c-martinez** [comment]
👍 -- ready to merge

**Pull request merged**
