### PR TITLE
Add a reference to the new Python template

### PR DESCRIPTION
**Pull request by jvdzwaan**
- [x] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

Below, describe what this Pull Request adds:

* Add a reference to the new Python template

### CODE REVIEW

**Comment by jspaaks** [comment]
Note that the guide was green not too long ago
https://travis-ci.org/NLeSC/guide/builds
When merging, we should make sure that the link checker returns green (if not at the Travis, at least locally)

**Comment by jvdzwaan** [comment]
Well, how do you do that? The link I added was not the problem...

**Comment by jspaaks** [comment]
How to run the link checker locally is described in the CONTRIBUTING guidelines 
https://github.com/NLeSC/guide/blob/master/CONTRIBUTING.md

**Comment by jvdzwaan** [comment]
The problem is not running the link analyzer, but what to do when links are marked as down (which is what always happens).

**Comment by jspaaks** [comment]
I agree the link checker is not perfect, but we should be careful not to start taking the failing travis to mean you don't need to check at all. When merging, it's worth (manually) going over the 5-10 links that failed, and see if they should be changed or if it's simply a matter of travis weirdness/blc weirdness/timeout/redirects/whathaveyou.

**Comment by LourensVeen** [comment]
For me, the issue here is that the CI on a pull request should check whether that pull request breaks anything. As it is, it checks that, but also checks whether changes outside of the code base have broken it, and then you're expecting people to add completely unrelated link fixes into their pull request. That just doesn't make sense to me.

Since links break all the time, and are usually unrelated to changes in the code, I would prefer to not check links in pull request (unless it can be done specifically on newly added links, that would be even better), and just set up a regular link check and assign someone to fix any reported broken links.

As a result, you may occasionally miss a broken link in a pull request, but it would be cleaned up quickly enough with all the other broken links. And at least you're not telling committers that their pull request is broken while there's nothing wrong with it.

**Comment by jspaaks** [comment]
I see what you mean but I think you're taking a somewhat strict point of view. Within that strict view, it is indeed customary to check the code base and not the outside world. However, taking a slightly relaxed view, you could see the PR as an opportune time for verifying the links: after all, at that time there is a developer who is available, has his/her environment set up, knows the steps for working with gitbooks, etc.

I don't find it problematic if the PR would get a commit history that says many things about adding sections and then ends with one or two 'fixed broken link' messages. To me this does not add any cognitive load to the main body of the PR. (Perhaps an argument could be if you don't want the main body of the PR , but do want the link fixes: this would be slightly more difficult). 

We have been discussing setting up link checking as a cron job on travis for periods when there are no pull request but the outside world changes. I can only tell you that with the experience we have so far, it seems difficult to assign people to fix broken links once you find any, but maybe that will change now that someone (@bouweandela) is in charge.

**Comment by LourensVeen** [comment]
Of course I'm taking a strict point of view :-). I see the practical aspect of it though. The main issue I was thinking of was that looking at the diff gets annoying if most of the changed files are unrelated link fixes.

We have chapter maintainers, right? Maybe it could be set up so that they get an email with this week's broken links in their chapter?

**Comment by jvdzwaan** [comment]
For me (as a chapter owner), having to fix broken links in sections I'm not in charge of and may know nothing about for each pull request I get, makes me want to put off merging (i.e., wait until someone else has done it).

**Comment by jspaaks** [comment]
@LourensVeen :) 
in practice I think there shouldn't be more than 1 broken link fix cluttering the diffs. I mean we have 3000+ links being checked and the most broken links I saw was about 35 (after a long period of neglect).

@jvdzwaan 
If it is just an obvious typo or copy-paste error like ``ttps://somewhere.com`` this shouldnt be a problem. If a resource has disappeared and you need to replace it with an equivalent one, then yes I can see your point, but I still think this should not be any reason why you can't merge. If the contents of the main body of the PR are an improvement, just merge. Probably, the [blc-good-enough thing](https://github.com/NLeSC/guide/blob/82946194bc186746ba8f0302bc42736e33199ed5/blc-good-enough.sh) will even mean that the PR is green. And anyway, this is how we have been working since we started the guide, merging PRs despite the fact they failed on travis as long as the main body of the PR was OK.

**Pull request merged**
