### PR TITLE
Generate PDF

### PR DESCRIPTION
**Pull request by sverhoeven**
- [x] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

Below, describe what this Pull Request adds:
After each push a GitHub Actions workflow will generate guide-nlesc.pdf and commit it to the repo.

### CODE REVIEW

**Comment by bouweandela** [comment]
Thanks @sverhoeven! Do you think we need to worry about filling the repo with large files like this?

**Comment by sverhoeven** [comment]
Ah yes, a 1Mb binary file will get added every push and in a 1000 pushes we will reach GH soft limit of 1Gb. That can be a problem cloning and getting poked by GH.

I see 2 alternatives:
1. Make PDF part of a new release, so we reduce the number of new PDF files
2. On each push to master upload the PDF somewhere else without versioning, but with a download link.

**Comment by bouweandela** [comment]
I think the second option would probably be best, because people will get confused if they're out of sync and also we do not do releases because honestly, who would want to read a very old version of the book (except for a software historian...?)

**Comment by c-martinez** [comment]
Sorry to jump in -- I think option #1 suggested by @sverhoeven (generate PDF on releases) could be a good idea.

Pros:
 - We could tie these releases with releases in zenodo
 - With zenodo releases we could add a DOI to the guide (discussed long ago #193)

Cons:
 - PDF will be not-the-latest-version (as rightly pointed by @bouweandela)

Mitigating argument:
 - If we do, for example, monthly releases, the PDF version is at most 1 month old, which may not be perfect, but could be acceptable.

What do you think?

**Comment by sverhoeven** [comment]
Could use https://github.com/iomega/zenodo-upload or https://github.com/svenstaro/upload-release-action

**Comment by bouweandela** [comment]
> PDF will be not-the-latest-version

This could be fixed by automatically making a new release after each merged pull request.

**Review by c-martinez — APPROVED** [review]
Great :-)

**Pull request merged**
