### PR TITLE
Remove the Publishing chapter

### PR DESCRIPTION
**Pull request by bouweandela**
I'm not sure if conferences and journals should also be removed, do we have another place for these and are they still relevant?

- Info on citable software is here: https://the-turing-way.netlify.app/communication/citable/citable-cite#cm-citable-cite-software
- Info on research data management is here: https://the-turing-way.netlify.app/reproducible-research/rdm

Related to #286

### CODE REVIEW

**Review by egpbos — COMMENTED** [review]
Most of this is great, good cleanup. The one thing I am in doubt of is the lists of publication venues, i.e. preprint archives, conferences and journals. I think this could still be a valuable list to keep. It can be a single top-level page, maybe called "Publication and dissemination venues" or something similar. What do you think?

**Comment by bouweandela** [comment]
Maybe the NL-RSE website would be a good place for a list of conferences and journals targeting RSEs https://github.com/nl-rse/website/issues/58

**Comment by egpbos** [comment]
Oh that's a great idea!

**Review by egpbos — APPROVED** [review]
With the suggestion of moving publication venues / conferences to the NL-RSE website, this PR LGTM!

**Pull request merged**
