### PR TITLE
First version of the Intellectual Property chapter

### PR DESCRIPTION
**Pull request by LourensVeen**
Here it is, finally. I've tried to cover enough to answer the questions I've had so far, but no more. Worked out okay I think (but yes, it's still the size of a good-sized research article...).

I've tried to split it up into more or less independent components so it can easily be used as a reference, but you can read it front to back as well.

Comments welcome!

### CODE REVIEW

**Comment by nielsdrost** [comment]
He Lourens, feel free to merge this yourself once you are happy with it (as you are the chapter owner of the IP chapter)

**Comment by LourensVeen** [comment]
I am happy with it :-). So let's merge it, we can always make further improvements later.

**Comment by LourensVeen** [comment]
Hold on, wait a minute, I'm not authorised to merge into master, since it's a protected branch. Could you do the honours?

**Comment by nielsdrost** [comment]
My bad, you mysteriously disappeared from the chapter owner team, which is able to merge to master.

You should be able to merge to master yourself now.

At least, if the status check from GitBook was working :-(

**Comment by nielsdrost** [comment]
Merging anyway

**Pull request merged**
