### PR TITLE
Remove outdated code review GitHub add-ons list

### LINKED ISSUE #86: Too many options for "GitHub add-ons" in Code Review section
There are 13 options listed for "GitHub Add ons" in the Code Review section.

This is too many. Could we limit the selection to things we have experience with and that work well?

### PR DESCRIPTION
**Pull request by LourensVeen**
Fixes #86.

### CODE REVIEW

**Comment by LourensVeen** [comment]
Huh? What conflict?

**Comment by nielsdrost** [comment]
You deleted a section which I already deleted a portion from. :-)

**Comment by LourensVeen** [comment]
Ah, guess I misinterpreted the diff :). And wasn't fast enough...let's merge this then?

**Comment by nielsdrost** [comment]
Fixed, Merged, thanks!

**Pull request merged**
